"""Optional Hugging Face ecosystem interoperability helpers.

These helpers intentionally import Hugging Face libraries lazily so the base
``great-generator`` installation remains lightweight. They never upload data.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from contextlib import suppress
from datetime import date
from typing import Any

import pandas as pd

HF_DATASETS_EXTRA = 'Install with: pip install "great-generator[hf]"'


def to_hf_dataset(
    data: pd.DataFrame,
    *,
    preserve_index: bool = False,
    metadata: Mapping[str, Any] | None = None,
) -> Any:
    """Convert a pandas DataFrame into a Hugging Face ``Dataset``.

    Hugging Face dependencies are optional and imported only when this helper is
    called. The helper performs a local conversion only; it does not upload to the
    Hugging Face Hub and does not require a token.
    """

    datasets = _load_datasets()
    if not isinstance(data, pd.DataFrame):
        raise TypeError("to_hf_dataset expects a pandas DataFrame.")
    dataset = datasets.Dataset.from_pandas(data, preserve_index=preserve_index)
    _attach_metadata(dataset, metadata)
    return dataset


def to_hf_dataset_dict(
    data: Mapping[str, pd.DataFrame],
    *,
    preserve_index: bool = False,
    metadata: Mapping[str, Any] | None = None,
) -> Any:
    """Convert a mapping of table names to Hugging Face ``DatasetDict``.

    This is useful for relational synthetic outputs, such as customers/orders or
    dimension/fact tables. Each table becomes one named split-like entry in the
    returned ``DatasetDict``.
    """

    datasets = _load_datasets()
    if not isinstance(data, Mapping) or not data:
        raise ValueError(
            "to_hf_dataset_dict expects a non-empty mapping of table names to DataFrames."
        )
    converted = {}
    for name, frame in data.items():
        table_metadata = _metadata_for_table(metadata, str(name))
        converted[str(name)] = to_hf_dataset(
            frame,
            preserve_index=preserve_index,
            metadata=table_metadata,
        )
    dataset_dict = datasets.DatasetDict(converted)
    _attach_metadata(dataset_dict, metadata)
    return dataset_dict


def generate_hf_dataset_card(
    *,
    dataset_name: str,
    domain: str | None = None,
    row_counts: Mapping[str, int] | None = None,
    schema_summary: Mapping[str, Any] | Sequence[str] | str | None = None,
    generation_method: str = "great-generator",
    synthetic: bool = True,
    generation_settings: Mapping[str, Any] | None = None,
    seed: int | None = None,
    intended_use: Sequence[str] | None = None,
    not_intended_use: Sequence[str] | None = None,
    limitations: Sequence[str] | None = None,
    license: str = "MIT",
    citation: str | None = None,
    repo_url: str = "https://github.com/GreatDataLabs/great-generator",
    how_to_regenerate: str | None = None,
    created_by: str = "Great Generator",
) -> str:
    """Generate Markdown for a Hugging Face dataset README/card.

    The generated card is documentation text only. It makes the synthetic nature
    of the dataset explicit and avoids privacy or production-data claims.
    """

    if not dataset_name or not str(dataset_name).strip():
        raise ValueError("dataset_name is required.")
    settings = dict(generation_settings or {})
    if seed is not None:
        settings.setdefault("seed", seed)
    intended = list(intended_use or ["data engineering demos", "testing", "analytics examples"])
    not_intended = list(
        not_intended_use
        or [
            "production analytics",
            "training models for real-world decision making",
            "privacy anonymization claims",
        ]
    )
    limits = list(
        limitations
        or [
            "Synthetic data only",
            "Does not represent real people, customers, accounts, or events",
            "Does not reproduce production distributions unless explicitly configured",
        ]
    )

    lines: list[str] = []
    lines.extend(
        [
            "---",
            f"license: {license}",
            "tags:",
            "- synthetic-data",
            "- data-generation",
            "- test-data",
            "- great-generator",
            "---",
            "",
            f"# {dataset_name}",
            "",
            (
                _synthetic_notice()
                if synthetic
                else "This dataset card was generated for a dataset produced with Great Generator."
            ),
            "",
            "## Dataset summary",
            "",
            f"- **Generated by**: {created_by}",
            f"- **Generation method**: {generation_method}",
        ]
    )
    if domain:
        lines.append(f"- **Domain**: {domain}")
    if seed is not None:
        lines.append(f"- **Seed**: {seed}")
    lines.append(f"- **Created**: {date.today().isoformat()}")
    lines.append("")

    lines.extend(["## Schema summary", ""])
    lines.extend(_render_schema_summary(schema_summary))
    lines.append("")

    lines.extend(["## Row counts", ""])
    if row_counts:
        lines.extend(["| Table | Rows |", "|---|---:|"])
        for name, count in sorted(row_counts.items(), key=lambda item: str(item[0])):
            lines.append(f"| {name} | {int(count)} |")
    else:
        lines.append("Row counts were not provided.")
    lines.append("")

    lines.extend(["## Generation settings", ""])
    if settings:
        for key, value in sorted(settings.items(), key=lambda item: str(item[0])):
            lines.append(f"- **{key}**: `{value}`")
    else:
        lines.append("Generation settings were not provided.")
    lines.append("")

    lines.extend(["## Intended use", ""])
    lines.extend(_bullets(intended))
    lines.append("")

    lines.extend(["## Not intended use", ""])
    lines.extend(_bullets(not_intended))
    lines.append("")

    lines.extend(["## Limitations", ""])
    lines.extend(_bullets(limits))
    lines.append("")

    lines.extend(
        [
            "## Responsible use",
            "",
            "Use this dataset for non-production demos, tests, tutorials, validation workflows, and experiments where synthetic data is appropriate. Do not treat it as evidence about real users, customers, patients, transactions, systems, or populations.",
            "",
            "## How to regenerate",
            "",
            how_to_regenerate
            or "Regenerate the dataset with Great Generator using the same schema, generation settings, and seed documented above.",
            "",
            "## Project links",
            "",
            f"- Great Generator repository: {repo_url}",
            "- PyPI package: https://pypi.org/project/great-generator/",
            "",
            "## Citation",
            "",
            citation
            or f"If this dataset is useful in a demo, tutorial, or experiment, cite Great Generator and link to {repo_url}.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _load_datasets() -> Any:
    try:
        import datasets
    except ImportError as exc:  # pragma: no cover - exact environment dependent
        raise ImportError(
            f"Hugging Face Datasets support is optional. {HF_DATASETS_EXTRA}"
        ) from exc
    return datasets


def _attach_metadata(target: Any, metadata: Mapping[str, Any] | None) -> None:
    if not metadata:
        return
    payload = dict(metadata)
    info = getattr(target, "info", None)
    if info is not None:
        for key in ("description", "citation", "homepage", "license"):
            if key in payload and hasattr(info, key):
                with suppress(Exception):
                    setattr(info, key, str(payload[key]))
    with suppress(Exception):
        target.great_generator_metadata = payload


def _metadata_for_table(
    metadata: Mapping[str, Any] | None, table_name: str
) -> Mapping[str, Any] | None:
    if not metadata:
        return None
    candidate = metadata.get(table_name) if isinstance(metadata, Mapping) else None
    if isinstance(candidate, Mapping):
        return candidate
    return metadata


def _render_schema_summary(
    schema_summary: Mapping[str, Any] | Sequence[str] | str | None,
) -> list[str]:
    if schema_summary is None:
        return ["Schema summary was not provided."]
    if isinstance(schema_summary, str):
        return [schema_summary]
    if isinstance(schema_summary, Mapping):
        lines = ["| Field | Description |", "|---|---|"]
        for key, value in sorted(schema_summary.items(), key=lambda item: str(item[0])):
            lines.append(f"| {key} | {value} |")
        return lines
    return _bullets([str(item) for item in schema_summary])


def _bullets(values: Sequence[str]) -> list[str]:
    return [f"- {item}" for item in values]


def _synthetic_notice() -> str:
    return (
        "**Synthetic data notice:** This dataset is synthetic. It was generated by Great "
        "Generator. It is not production data, and it is not an anonymized, masked, or "
        "de-identified copy of production records."
    )
